from __future__ import annotations
from typing import Protocol, Any, Mapping


class ChatCallbacks(Protocol):
    """События цикла диалога. Реализация решает, как их показывать."""

    def on_thinking(self, chunk: str) -> None: ...
    def on_content(self, chunk: str) -> None: ...
    def on_tool_call(self, name: str, arguments: Mapping[str, Any]) -> None: ...
    def on_tool_result(self, name: str, result: str) -> None: ...
    def on_context_size(self, tokens: int) -> None: ...
    def on_empty_response(self) -> None: ...
    def on_iteration_limit(self, limit: int) -> None: ...
